import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, cpSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { createServer } from '../src/server.js';

test('editor stays static, reports errors, and clicks finish steps before custom page transition', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'vw-motion-ui-'));
  const server = createServer({ dataDir: dir });
  cpSync(new URL('../examples/sample-deck/', import.meta.url), join(dir, 'projects/sample-deck'), { recursive: true, filter: name => !String(name).includes('/versions') });
  const file = join(dir, 'projects/sample-deck/project.json');
  const project = JSON.parse(readFileSync(file, 'utf8'));
  project.pages[0].elements.find(e => e.id === 'el_title1').x = 321;
  project.pages[0].motion = { steps: 2, source: `export default ctx => {
    const {node,base}=ctx.element('el_title1'); node.style.opacity='0';
    return {step(index){node.style.opacity='1';node.style.left=(base.x+(index+1)*10)+'px';},
      transition({to,direction}){to.dataset.arrival=String(direction);}};
  }` };
  project.pages[1].motion = { steps: 0, source: 'export default () => ({})' };
  project.pages[2].motion = { steps: 1, source: 'export default () => ({ step(){throw new Error("intentional motion failure")} })' };
  writeFileSync(file, JSON.stringify(project));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let browser;
  t.after(async () => { await browser?.close(); await new Promise(resolve => server.close(resolve)); rmSync(dir, { recursive: true, force: true }); });
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.locator('[data-action="open"][data-id="sample-deck"]').click();
  const title = page.locator('#artboard [data-element-id="el_title1"]');
  assert.equal(await title.evaluate(n => n.style.left), '321px');
  assert.equal(await title.evaluate(n => n.style.opacity), '1');
  await page.getByText('动效检查未通过', { exact: true }).waitFor();
  assert.match(await page.locator('.ed-toolbar .ed-note').textContent(), /intentional motion failure/);
  await page.locator('[data-action="play"]').click();
  await page.waitForSelector('#player-stage [data-page-id="page_cover1"]');
  await page.waitForFunction(() => document.querySelector('#player-stage [data-element-id="el_title1"]').style.opacity === '0');
  await page.keyboard.press('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#player-stage [data-element-id="el_title1"]').style.left === '331px');
  assert.equal(await page.locator('#player-page').textContent(), '1 / 3');
  await page.keyboard.press('ArrowRight');
  await page.waitForFunction(() => document.querySelector('#player-stage [data-element-id="el_title1"]').style.left === '341px');
  assert.equal(await page.locator('#player-page').textContent(), '1 / 3');
  await page.keyboard.press('ArrowRight');
  await page.waitForSelector('#player-stage [data-page-id="page_scene2"][data-arrival="1"]');
  await page.keyboard.press('Escape');
  await page.waitForSelector('#artboard');
  assert.equal(await title.evaluate(n => n.style.left), '321px');
  assert.equal(await title.evaluate(n => n.style.opacity), '1');
  assert.deepEqual(JSON.parse(readFileSync(file, 'utf8')), project);
  assert.deepEqual(errors, []);
});
