import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {extractOutline,planApplyText,createOutline,addRow,toggleEmphasis,addScreen,isVisible,deletePage,copyBrief,reorderPages} from '../web/outline-model.js';
import {validateProjectData} from '../src/validate.js';
const fixture=()=>JSON.parse(readFileSync(new URL('../examples/sample-deck/project.json',import.meta.url)));
test('visibility extraction preserves noncontiguous actual frames and nested mapping',()=>{const p=fixture(),page=p.pages[0];page.motion={steps:2,source:'export default ()=>({step(){}})'};const e=page.elements.find(e=>e.type==='text');page.outline=extractOutline(p,page,{1:[e.id],2:[],3:[e.id]});const r=page.outline.rows[0];assert.deepEqual(r.visibleOn,[1,3]);assert.equal(isVisible(r,2),false);assert.equal(validateProjectData(p).ok,true);});
test('only mapped text is applied, structural changes and deleted rows are reported',()=>{const p=fixture(),page=p.pages[0];page.outline=extractOutline(p,page);const before=structuredClone(page.elements),r=page.outline.rows[0];r.text+=' edited';r.role='note';page.outline.rows.pop();addRow(page.outline,'body',1,'new');const plan=planApplyText(p,[page.id]);assert.ok(plan.applied.length);assert.ok(plan.changes.some(c=>c.type==='role'));assert.ok(plan.changes.some(c=>c.type==='new'));assert.ok(plan.changes.some(c=>c.type==='deleted'));assert.deepEqual(p.pages[0].elements,before);const el=plan.project.pages[0].elements.find(e=>e.id===r.elementId);assert.equal(el.text,r.text);assert.equal(el.x,before.find(e=>e.id===r.elementId).x);});
test('canvas manual text conflicts are untouched',()=>{const p=fixture(),page=p.pages[0];page.outline=extractOutline(p,page);const r=page.outline.rows[0],e=page.elements.find(e=>e.id===r.elementId);r.text='outline';e.text='manual';const plan=planApplyText(p);assert.ok(plan.changes.some(c=>c.type==='text-conflict'));assert.equal(plan.project.pages[0].elements.find(e=>e.id===r.elementId).text,'manual');});
test('range emphasis editing, inherited screens, and minimum page count',()=>{const o=createOutline(),r=addRow(o,'body',1,'abcdef');toggleEmphasis(r,1,5);toggleEmphasis(r,2,3);assert.deepEqual(r.emphasis,[{start:1,end:2},{start:3,end:5}]);addScreen(o);assert.equal(isVisible(r,2),true);assert.equal(deletePage({pages:[{id:'one'}]},'one'),false);});
test('outline validation rejects bad ranges, unknown assets and ambiguity',()=>{const p=fixture(),page=p.pages[0];page.outline=createOutline();const r=addRow(page.outline,'body',2,'abc');assert.equal(validateProjectData(p).ok,false);r.from=1;r.emphasis=[{start:0,end:4}];assert.equal(validateProjectData(p).ok,false);r.emphasis=[];r.elementId='el_fake1';const second=addRow(page.outline);second.elementId=r.elementId;assert.equal(validateProjectData(p).ok,false);page.outline.rows.pop();assert.equal(validateProjectData(p).ok,true);assert.ok(copyBrief(p,[page.id],'/tmp/project.json').includes('/tmp/project.json'));});

test('page ordering keeps ids and metadata, rejects incomplete or duplicate order',()=>{const project={pages:[{id:'first',outline:createOutline()},{id:'second',name:'Second'}]};const outline=project.pages[0].outline;reorderPages(project,['second','first']);assert.equal(project.pages[0].id,'second');assert.equal(project.pages[1].outline,outline);assert.throws(()=>reorderPages(project,['first','first']));assert.throws(()=>reorderPages(project,['first']));});
