import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,readFileSync,existsSync,mkdirSync,symlinkSync,utimesSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from './helpers/isolated-server.js';
import {cleanupTrash,RETENTION_MS} from '../src/project-management.js';
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'vw-management-'));const server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{if(server.listening)await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});const base='http://127.0.0.1:'+server.address().port;const request=async(path,method='GET',payload)=>{const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload)});return {status:r.status,body:await r.json()};};return {dir,request,server,base};}
test('rename preserves id and folder; full duplicate carries extras and content without history',async t=>{const {dir,request}=await fixture(t);const source=(await request('/api/projects','POST',{id:'source',name:'Source'})).body.project;const p=join(dir,'projects/source');writeFileSync(join(p,'assets/a.txt'),'asset');writeFileSync(join(p,'fonts/f.txt'),'font');writeFileSync(join(p,'motion.js'),'motion');writeFileSync(join(p,'outline.txt'),'outline');mkdirSync(join(p,'versions/history'));writeFileSync(join(p,'versions/history/file'),'version');writeFileSync(join(p,'pages/page_first.html'),'<!doctype html><body><h1 data-vw-id="title" data-vw="text move">副本保留的文案</h1></body>');source.pages[0].motion={steps:1};source.pages[0].notes='副本保留的页面备注';source.pages[0].edits=[{id:'ed_keep0001',target:'title',kind:'move',before:{x:0,y:0,width:100,height:40},after:{dx:10,dy:5}}];writeFileSync(join(p,'project.json'),JSON.stringify(source));const renamed=await request('/api/projects/source','PATCH',{name:' New '});assert.equal(renamed.body.project.name,'New');assert.equal(renamed.body.project.id,'source');assert.equal((await request('/api/projects/source','PATCH',{name:' '})).status,400);const copied=await request('/api/projects/source/duplicate','POST',{id:'copy-1'});assert.equal(copied.status,201);assert.equal(copied.body.project.id,'copy-1');assert.deepEqual(copied.body.project.pages,source.pages);assert.equal(copied.body.project.pages[0].edits[0].id,'ed_keep0001');assert.match(readFileSync(join(dir,'projects/copy-1/pages/page_first.html'),'utf8'),/副本保留的文案/);for(const file of ['assets/a.txt','fonts/f.txt','motion.js','outline.txt'])assert.ok(existsSync(join(dir,'projects/copy-1',file)));assert.ok(!existsSync(join(dir,'projects/copy-1/versions/history')));assert.equal((await request('/api/projects/source/duplicate','POST',{id:'copy-1'})).status,409);assert.equal((await request('/api/projects/source/duplicate','POST',{id:'../escape'})).status,400);});
test('trash restores masters and preserves other state; collision never overwrites; purge removes only entry',async t=>{const {dir,request}=await fixture(t);await request('/api/projects','POST',{id:'source',name:'Source'});writeFileSync(join(dir,'workbench-state.json'),JSON.stringify({masters:['source'],other:{x:1}}));const deleted=await request('/api/projects/source','DELETE',{});assert.equal(deleted.status,200);assert.ok(!existsSync(join(dir,'projects/source')));let state=JSON.parse(readFileSync(join(dir,'workbench-state.json')));assert.deepEqual(state,{masters:[],other:{x:1}});const rows=(await request('/api/trash')).body;assert.equal(rows.length,1);assert.equal(rows[0].master,true);await request('/api/projects','POST',{id:'source',name:'Collision'});assert.equal((await request('/api/trash/'+deleted.body.trashId+'/restore','POST',{})).status,409);assert.equal((await request('/api/projects/source')).body.project.name,'Collision');const second=(await request('/api/projects/source','DELETE',{})).body;assert.equal((await request('/api/trash/'+deleted.body.trashId+'/restore','POST',{})).status,200);state=JSON.parse(readFileSync(join(dir,'workbench-state.json')));assert.deepEqual(state,{masters:['source'],other:{x:1}});assert.equal((await request('/api/trash/'+second.trashId,'DELETE',{})).status,200);assert.equal((await request('/api/trash')).body.length,0);assert.equal((await request('/api/trash/trash-invalid','DELETE',{})).status,400);});
test('retention uses deletion metadata, keeps under seven days and cleans at seven days on startup',async t=>{const {dir,request,server}=await fixture(t);await request('/api/projects','POST',{id:'source',name:'Source'});const row=(await request('/api/projects/source','DELETE',{})).body;const folder=join(dir,'.trash',row.trashId),meta=join(folder,'meta.json');const now=new Date('2030-01-01T00:00:00Z');row.deletedAt=new Date(now-RETENTION_MS+1).toISOString();writeFileSync(meta,JSON.stringify(row));utimesSync(folder,0,0);assert.deepEqual(cleanupTrash(dir,{now}),[]);row.deletedAt=new Date(now-RETENTION_MS).toISOString();writeFileSync(meta,JSON.stringify(row));assert.deepEqual(cleanupTrash(dir,{now}),[row.trashId]);await request('/api/projects','POST',{id:'another',name:'Another'});const old=(await request('/api/projects/another','DELETE',{})).body;old.deletedAt='2000-01-01T00:00:00Z';writeFileSync(join(dir,'.trash',old.trashId,'meta.json'),JSON.stringify(old));await new Promise(r=>server.close(r));const second=createServer({dataDir:dir});second.close();assert.ok(!existsSync(join(dir,'.trash',old.trashId)));});
test('project, state and trash symlinks are rejected without touching targets',async t=>{const {dir,request}=await fixture(t);await request('/api/projects','POST',{id:'source',name:'Source'});const outside=join(dir,'outside');mkdirSync(outside);writeFileSync(join(outside,'keep'),'safe');try{symlinkSync(outside,join(dir,'projects/source/link'));}catch(e){if(process.platform!=='win32'||e.code!=='EPERM')throw e;t.diagnostic('Windows 未开启开发者模式或管理员权限，无法创建符号链接；本用例只省略链接安全检查，其他回收、复制、存版测试照常执行');assert.equal(readFileSync(join(outside,'keep'),'utf8'),'safe');assert.ok(existsSync(join(dir,'projects/source/project.json')));return;}assert.equal((await request('/api/projects/source/duplicate','POST',{})).status,403);assert.equal((await request('/api/projects/source','DELETE',{})).status,403);rmSync(join(dir,'projects/source/link'));symlinkSync(join(outside,'keep'),join(dir,'workbench-state.json'));assert.equal((await request('/api/projects/source','DELETE',{})).status,403);rmSync(join(dir,'workbench-state.json'));const row=(await request('/api/projects/source','DELETE',{})).body;symlinkSync(outside,join(dir,'.trash',row.trashId,'link'));assert.equal((await request('/api/trash/'+row.trashId,'DELETE',{})).status,403);assert.equal((await request('/api/trash/'+row.trashId+'/restore','POST',{})).status,403);assert.equal(readFileSync(join(outside,'keep'),'utf8'),'safe');});
test('new mutation routes retain same-origin and active-session protections',async t=>{const {dir,request,base}=await fixture(t);await request('/api/projects','POST',{id:'source',name:'Source'});for(const [path,method] of [['/api/projects/source','PATCH'],['/api/projects/source','DELETE'],['/api/projects/source/duplicate','POST'],['/api/trash','GET']]){const r=await fetch(base+path,{method,headers:{Origin:'http://evil.test'},body:method==='GET'?undefined:'{}'});assert.equal(r.status,403);}const now=new Date().toISOString();writeFileSync(join(dir,'.workbench-sessions','other.json'),JSON.stringify({sessionId:'other',computer:'Other',startedAt:now,updatedAt:now}));assert.equal((await request('/api/projects/source','DELETE',{})).status,423);assert.equal((await request('/api/projects/source','PATCH',{name:'Changed'})).status,423);assert.equal((await request('/api/projects/source/duplicate','POST',{})).status,423);assert.equal((await request('/api/trash')).status,423);assert.ok(existsSync(join(dir,'projects/source')));});

test('blocked startup defers retention cleanup until the user confirms active sessions',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'vw-blocked-trash-'));let server;
 t.after(async()=>{if(server?.listening)await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});
 server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base='http://127.0.0.1:'+server.address().port;
 await fetch(base+'/api/projects',{method:'POST',body:JSON.stringify({id:'source',name:'Source'})});const deleted=await(await fetch(base+'/api/projects/source',{method:'DELETE',body:'{}'})).json();await new Promise(r=>server.close(r));
 const meta=join(dir,'.trash',deleted.trashId,'meta.json');const record=JSON.parse(readFileSync(meta));record.deletedAt='2000-01-01T00:00:00Z';writeFileSync(meta,JSON.stringify(record));const now=new Date().toISOString();
 writeFileSync(join(dir,'.workbench-sessions','other.json'),JSON.stringify({sessionId:'other',computer:'Other',startedAt:now,updatedAt:now}));
 server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
 const status=await(await fetch(base+'/api/session')).json();assert.equal(status.blocked,true);assert.ok(existsSync(meta));
 const result=await fetch(base+'/api/session/confirm',{method:'POST',body:JSON.stringify({tokens:status.fresh.map(s=>s.token)})});assert.equal(result.status,200);assert.equal((await result.json()).blocked,false);assert.equal(existsSync(meta),false);
});
