import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtempSync,rmSync,readdirSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from './helpers/isolated-server.js';
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'vw-close-'));const server=createServer({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{if(server.listening)await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true});});return {dir,server,url:'http://127.0.0.1:'+server.address().port};}
test('shutdown removes own session, stops server and keeps imported test process alive',async t=>{const {dir,server,url}=await fixture(t);assert.equal(readdirSync(join(dir,'.workbench-sessions')).length,1);const closed=new Promise(r=>server.once('close',r));const r=await fetch(url+'/api/shutdown',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,200);assert.deepEqual(await r.json(),{closed:true});await closed;assert.equal(server.listening,false);assert.equal(readdirSync(join(dir,'.workbench-sessions')).length,0);});
test('shutdown rejects hostile origin and malformed body, leaves server running',async t=>{const {server,url}=await fixture(t);for(const [headers,body,status] of [[{Origin:'http://evil.test'},'{}',403],[{},'not-json',400]]){const r=await fetch(url+'/api/shutdown',{method:'POST',headers,body});assert.equal(r.status,status);}assert.equal(server.listening,true);});
test('shutdown rechecks session after delayed body and preserves foreign marker',async t=>{const {dir,server,url}=await fixture(t);const marker=join(dir,'.workbench-sessions','foreign.json');const request=http.request(url+'/api/shutdown',{method:'POST',headers:{'Content-Type':'application/json'}});const response=new Promise(resolve=>request.on('response',r=>{r.resume();r.on('end',()=>resolve(r.statusCode));}));request.write('{');await new Promise(r=>setTimeout(r,20));writeFileSync(marker,JSON.stringify({sessionId:'foreign',hostname:'Other',computer:'Other',pid:999,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}));request.end('}');assert.equal(await response,423);assert.equal(server.listening,true);assert.ok(readdirSync(join(dir,'.workbench-sessions')).includes('foreign.json'));});
test('shutdown rejects already waiting writes after releasing its usage marker',async t=>{const {server,url}=await fixture(t);await fetch(url+'/api/projects',{method:'POST',body:JSON.stringify({id:'source',name:'Source'})});const request=http.request(url+'/api/projects/source',{method:'PATCH',headers:{'Content-Type':'application/json'}});const response=new Promise(resolve=>request.on('response',r=>{r.resume();r.on('end',()=>resolve(r.statusCode));}));request.write('{');await new Promise(r=>setTimeout(r,20));const closed=new Promise(r=>server.once('close',r));assert.equal((await fetch(url+'/api/shutdown',{method:'POST',body:'{}'})).status,200);request.end('"name":"Too late"}');assert.equal(await response,503);await closed;});
